### ISSUE TITLE
Sample file requirements

### ISSUE THREAD

**Issue by P2Oileen** [ljsabc/Fujisaki#1]
感谢您为社区贡献了非常有趣的工作！我一直在关注您的进展，非常希望可以复现这个repo，但是我并没有活跃的推特账号和内容，我希望能用其他平台的数据进行训练。请问您是否可以提供一个示例的推文存档，或者如readme中所提到的tweets.md文件的示例呢？里面可以只包含几条数据，这样我就可以尝试将其他平台的数据以相同的方式组织起来，用于finetune模型了。

**Comment by Anthony-Hoo** [comment]
我之前也很困惑这个问题，因为推特导出数据需要等24h，就去看了下源码。
喂进来的数据集大概是和[上游](https://raw.githubusercontent.com/mymusise/ChatGLM-Tuning/master/data/alpaca_data.json)一致的，类似于这种格式：
```json
[
    {
        "instruction": "吃了吗",
        "input": "",
        "output": "吃了哦"
    },
    {
        "instruction": "",
        "input": "",
        "output": ""
    }
]
```
把你的数据转换成此格式，保存到 tweets.md 就可以跑下去了。

**Comment by ljsabc** [comment]
请参照tweets_sample.md（其实是个json，但是现在懒得改了），另外也可以参看prompt_basic.py了解数据到底是怎么处理的。
数据和上游的格式是一致的。如果是回复类推文，则使用\n作为简单分隔符（方便处理+不想刻意区分角色）。

**Comment by ljsabc** [comment]
很快我又收到了#2

看起来后续的计划是要将项目重构成不同的parser+同样的data生成器的模式了。如果是这样也欢迎各位提出自己的data parser，用来处理各种各样的数据，这样就也许可以更方面地生成大家想要的语料。
欢迎大家来#2探讨。
